# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/149tmM9mG96xZYqqE0DH4Qly_X4pZJCgh
"""

import os


def processar_resposta(resposta, nome):
    if resposta == '1':
        print(f'{os.linesep}{nome}, 25 de Setembro de 2021{os.linesep}')
    elif resposta == '2':
        print(f'{os.linesep}{nome}, Dia do Rádio{os.linesep}')
    elif resposta == '3':
        print(f'{os.linesep}{nome}, John Henry Bonham foi um músico e compositor inglês, mais conhecido por ter sido o baterista da banda Led Zeppelin.{os.linesep}')
    elif resposta == '4':
        print(f'{os.linesep}{nome}, Stairway To Heaven Led Zeppelin IV · 1971{os.linesep}')
    else:
        print('Digite apenas 1, 2, 3 ou 4')


def start():
    # Apresentar o chatbot
    print('Olá! Bem-vindo')
    # pedir o nome
    nome = input('Digite seu nome: ')
    # pedir o e-mail
    email = input('Digite seu e-mail: ')
    while True:
        # Oferer o menu de opções
        resposta = input(
            f'O que gostaria de saber hoje?{os.linesep}[1] - Qual a data de hoje?{os.linesep}[2] - O que é comemorado no dia de hoje?{os.linesep}[3] - Quem morreu hoje?{os.linesep}[4] - Música do dia')
        # Processar a resposta enviada
        processar_resposta(resposta, nome)


if __name__ == '__main__':
    start()